### ISSUE TITLE
Disable daily email reports

### ISSUE THREAD

**Issue by pblair12** [pblair12/mosaic-groups#17]
Heroku is getting wise to us using pingdom and newrelic, which were both pinging our production server on a regular basis.  This was keeping the production server alive and enabling it to send out the daily email report at 11:59GMT.  Unless we upgrade our Heroku server to a paid version we need to stop those services.  That means we should disable the daily email reports since there is no guarantee that the server will be up at the time that the report needs to be sent.

Here is the message we are receiving from Heroku

"Hi,

Your app mosaicgroups is running on free dynos and has been active for more than 18 of the last 24 hours. Normally, your app would recharge for the next 6 hours. Don't worry, your app is still running. Right now we're simply sending notifications.

Why are you receiving this and what can you do?

Your app is becoming more popular. Upgrade your app to Hobby dynos for $7 per dyno per month so it never sleeps and users can access it 24×7.

A monitoring service could unintentionally be keeping your app awake for more than 18 hours a day. Run heroku logs -t to view your app's logs to see if this is the case and remove Pingdom, New Relic or other availability monitoring services that are not required for a free development app.

Your application may be receiving traffic from some other automated source. In order to sync up your app's sleep cycle with your own, scale it down before going to bed. In the morning, turn your app back on.

Your application may not have a web process at all. Once worker-only apps are started, they run for 18 hours and then recharge for 6 hours. After this your dynos will be started again. You can avoid this by upgrading to a hobby dyno, or by manually scaling down your application for six hours at a time that is convenient for you.

Dyno sleeping lets us provide you and millions of other users with a free tier for experimenting, hacking on personal projects and even low traffic apps that don't require 24×7 access.

We're here to help and would love hear from you or answer any questions at help.heroku.com or pricing-feedback@heroku.com!

Happy coding, Heroku"

**Comment by pblair12** [comment]
I verified that the emails have been disabled by checking that the following was output in the logs when I deployed the change:

Aug 24 01:42:40 mosaicgroups app/web.1:  Group reports are currently disabled 
Aug 24 01:42:40 mosaicgroups app/web.1:  Distinct members reports are currently disabled 

I also disabled pingdom's pinging of our server.

@jeffklassen could you please disable newrelic?  Thanks!!

**Comment by jeffklassen** [comment]
Complete.
