### ISSUE TITLE
Member Limit Sign Up

### ISSUE THREAD

**Issue by pblair12** [pblair12/mosaic-groups#29]
<from Amanda>

>
Hey guys,
For next semester, is it possible to limit a person's ability to sign up for groups to two groups per person? We're having people sign up for a ton, take spots, and then drop out, so I'm trying to cut down on that.
Let me know what you think!

**Comment by jeffklassen** [comment]
Since group member's are added on the fly - do we want to distinguish individual members by email address?

**Comment by pblair12** [comment]
yes

On Sun, Jan 3, 2016 at 6:25 AM, Jeff <notifications@github.com> wrote:

> Since group member's are added on the fly - do we want to distinguish
> individual members by email address?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pblair12/mosaic-groups/issues/29#issuecomment-168489877>
> .
>



-- 
Pat Blair
AdventuresForTheCure
http://adventuresforthecure.com
http://pblair12.blogspot.com/
https://github.com/pblair12

**Comment by jeffklassen** [comment]
Also, we probably want leaders to be able to join multiple groups

**Comment by jeffklassen** [comment]
Closed by accident!

**Comment by jeffklassen** [comment]
I'd like to close this, but given the fact that I have not pushed to heroku in forever, would appreciate it if @pblair12 would take a look first.

**Comment by pblair12** [comment]
Looks like we got a few people who were caught by this new feature yesterday.  I received 3 emails stating "Error: You have signed up for the maximum number of groups." Those emails were addressed to myself, Jessica Coleman, and Jeff.  Were these tests or actual people trying to register for > 2 groups?  I was thinking maybe we should update the emails so that it would specify who was trying to register for > 2 groups.  If we did that then Jessica or someone could follow up with that person if they wanted to.

**Comment by pblair12** [comment]
Just to clarify what I was saying in our chat yesterday.  The refactoring you did by putting this logic in the model is fine but eventually if we really want to refactor things a bit better we should remove all of the business logic out of our controllers and model objects and put them where they belong in the service layer (which does not exist in our project currently).  We would want the following in server/services: groupsService, settingsService, and usersService.  This is not critical but it would make the code much more modular and more like proper MVC ;)

**Comment by jeffklassen** [comment]
When I was testing, I did not have any email server credentials specified, so no emails were sent. These were likely legitimate 'catches'.

**Comment by pblair12** [comment]
I am going to reopen this issue so we can add the name/email of the person who made the attempt to register for > 2 groups in the email that is sent to the admins.  I think that would be a really nice to have.

**Comment by pblair12** [comment]
hm... let me make a new issue instead :)
