### ISSUE TITLE
Set up service to monitor mosaicgroups.org for up-ness

### ISSUE THREAD

**Issue by jeffklassen** [pblair12/mosaic-groups#7]
Send emails to pat and I if ping fails. Must auto restart on server reboot.

**Comment by jeffklassen** [comment]
@pblair12 Do we still want to do this given heroku's newer uptime limitations?

**Comment by pblair12** [comment]
It would be awesome to have some way to 'wake up' mosaicgroups.org everyday at a specific time so that the server would be guaranteed to send out a report/email every day at that time.  But keeping the server up at all times is not something we can do anymore.

**Comment by jeffklassen** [comment]
It should be easy on a linux machine to schedule a crontab to ```ping -T 5``` at a given time. How long do these heroku instances stay up for once awoken?

**Comment by pblair12** [comment]
I don't know

**Comment by pblair12** [comment]
Certainly it will be up long enough after we wake it up to send a report email.

**Comment by jeffklassen** [comment]
Im going to close this ticket and create a new one with the specifications @pblair12  laid out in his latest comment.
